const affirmations = [
  { id: 0, text: "Ich darf mir Zeit für mich nehmen." },
  { id: 1, text: "Ich erlaube mir, Fehler zu machen und aus ihnen zu lernen." },
  { id: 2, text: "Ich bin stolz auf meine Erfolge." },
  {
    id: 3,
    text: "Ich kümmere mich liebevoll um meinen Körper und meine Gesundheit.",
  },
  {
    id: 4,
    text: "Ich setze kleine, gesunde Gewohnheiten um, um mein Wohlbefinden zu verbessern.",
  },
  { id: 5, text: "Ich bin offen für liebevolle Beziehungen, die mir guttun." },
  {
    id: 6,
    text: "Ich bin dankbar für die kleinen Freuden des Lebens, die mich umgeben.",
  },
  { id: 7, text: "Ich atme tief ein und aus und lasse alle Anspannung los." },
  { id: 8, text: "Ich nehme mich so an wie ich bin." },
  { id: 9, text: "Ich verdiene es, Erfolg zu haben." },
  { id: 10, text: "Ich kann aus allem das Beste rausholen." },
  { id: 11, text: "Ich schätze, was ich habe." },
  { id: 12, text: "Ich bin liebenswert." },
  { id: 13, text: "Es ist okay, auch mal Angst zu haben." },
  { id: 14, text: "Die Quelle meiner Kraft liegt in mir." },
  { id: 15, text: "Ich feiere meine Stärken und akzeptiere meine Schwächen." },
  { id: 16, text: "Ich schaffe das." },
  { id: 17, text: "Jeder Tag bringt neue Möglichkeiten." },
  { id: 18, text: "Ich gestalte mein eigenes Glück." },
  { id: 19, text: "Ich öffne mich dafür, dass jeder Tag ein guter Tag wird." },
  { id: 20, text: "Ich kann mir und anderen verzeihen." },
  { id: 21, text: "Ich darf schlechte Tage und Misserfolge haben." },
  { id: 22, text: "Ich finde immer einen Weg, die Dinge zu lösen." },
  { id: 23, text: "Ich bin mutig." },
  { id: 24, text: "Ich bin mein größter Cheerleader." },
  { id: 25, text: "Ich kenne meine Grenzen und stehe für sie ein." },
  { id: 26, text: "Ich darf schlechte Tage haben und mich trotzdem lieben." },
  { id: 27, text: "Ich bin genug, auch wenn ich es mal nicht fühle." },
  { id: 28, text: "Ich achte auf mich und meine Bedürfnisse." },
  { id: 29, text: "Ich bin ein wertvoller Mensch." },
  {
    id: 30,
    text: "Ich nehme nichts selbstverständlich, sondern spüre Dankbarkeit.",
  },
  {
    id: 31,
    text: "Ich ärger mich nicht über Dinge, die ich nicht ändern kann.",
  },
  {
    id: 32,
    text: "Ich lasse die Vergangenheit los und denke an die Gegenwart.",
  },
  { id: 33, text: "Ich werde von Tag zu Tag besser." },
  { id: 34, text: "Ich darf mich verletzlich zeigen." },
  { id: 35, text: "Ich darf neue Wege gehen." },
  {
    id: 36,
    text: "Ich entscheide mich bewusst dafür, heute glücklich zu sein.",
  },
  { id: 37, text: "Ich öffne mich für neue Inspiration." },
  { id: 38, text: "Ich lächle, weil ich mich gut dadurch fühle." },
  {
    id: 39,
    text: "Ich achte auf mein Denken und wähle bewusst gesunde Gedanken.",
  },
  { id: 40, text: "Ich bin ein guter Freund." },
  { id: 41, text: "Ich darf um Hilfe bitten." },
];

export default affirmations;
